### ISSUE TITLE
assert when reconnect

### ISSUE THREAD

**Issue by ppwwiinn** [disarmyouwitha/bobber_bot#1]
thresh.py:214
with open(config_filename) as config_file:
                        configs = json.load(config_file)
we need to define config_filename in reconnect function

**Comment by disarmyouwitha** [comment]
Thank you! =D I must have missed this during config refactor.

https://github.com/disarmyouwitha/bobber_bot/commit/6b89646ee7a596c21fe42d2eca54b761901be51f
